// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: apu/mail_sender/mail_sender.proto

package mail_sender

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MailServerClient is the client API for MailServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailServerClient interface {
	SendStatisticServerToEmail(ctx context.Context, in *RequestSendStatisticServerToEmail, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mailServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMailServerClient(cc grpc.ClientConnInterface) MailServerClient {
	return &mailServerClient{cc}
}

func (c *mailServerClient) SendStatisticServerToEmail(ctx context.Context, in *RequestSendStatisticServerToEmail, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/MailServer/SendStatisticServerToEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServerServer is the server API for MailServer service.
// All implementations must embed UnimplementedMailServerServer
// for forward compatibility
type MailServerServer interface {
	SendStatisticServerToEmail(context.Context, *RequestSendStatisticServerToEmail) (*emptypb.Empty, error)
	mustEmbedUnimplementedMailServerServer()
}

// UnimplementedMailServerServer must be embedded to have forward compatible implementations.
type UnimplementedMailServerServer struct {
}

func (UnimplementedMailServerServer) SendStatisticServerToEmail(context.Context, *RequestSendStatisticServerToEmail) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendStatisticServerToEmail not implemented")
}
func (UnimplementedMailServerServer) mustEmbedUnimplementedMailServerServer() {}

// UnsafeMailServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailServerServer will
// result in compilation errors.
type UnsafeMailServerServer interface {
	mustEmbedUnimplementedMailServerServer()
}

func RegisterMailServerServer(s grpc.ServiceRegistrar, srv MailServerServer) {
	s.RegisterService(&MailServer_ServiceDesc, srv)
}

func _MailServer_SendStatisticServerToEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSendStatisticServerToEmail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServerServer).SendStatisticServerToEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MailServer/SendStatisticServerToEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServerServer).SendStatisticServerToEmail(ctx, req.(*RequestSendStatisticServerToEmail))
	}
	return interceptor(ctx, in, info, handler)
}

// MailServer_ServiceDesc is the grpc.ServiceDesc for MailServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MailServer",
	HandlerType: (*MailServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendStatisticServerToEmail",
			Handler:    _MailServer_SendStatisticServerToEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apu/mail_sender/mail_sender.proto",
}
