// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: apu/server_file/server_file.proto

package file

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UploadMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UploadMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UploadMessageMultiError, or
// nil if none found.
func (m *UploadMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Chunk

	if len(errors) > 0 {
		return UploadMessageMultiError(errors)
	}

	return nil
}

// UploadMessageMultiError is an error wrapping multiple validation errors
// returned by UploadMessage.ValidateAll() if the designated constraints
// aren't met.
type UploadMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadMessageMultiError) AllErrors() []error { return m }

// UploadMessageValidationError is the validation error returned by
// UploadMessage.Validate if the designated constraints aren't met.
type UploadMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadMessageValidationError) ErrorName() string { return "UploadMessageValidationError" }

// Error satisfies the builtin error interface
func (e UploadMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadMessageValidationError{}

// Validate checks the field values on ResponseEmpty with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ResponseEmpty) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResponseEmpty with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ResponseEmptyMultiError, or
// nil if none found.
func (m *ResponseEmpty) ValidateAll() error {
	return m.validate(true)
}

func (m *ResponseEmpty) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ResponseEmptyMultiError(errors)
	}

	return nil
}

// ResponseEmptyMultiError is an error wrapping multiple validation errors
// returned by ResponseEmpty.ValidateAll() if the designated constraints
// aren't met.
type ResponseEmptyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResponseEmptyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResponseEmptyMultiError) AllErrors() []error { return m }

// ResponseEmptyValidationError is the validation error returned by
// ResponseEmpty.Validate if the designated constraints aren't met.
type ResponseEmptyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResponseEmptyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResponseEmptyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResponseEmptyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResponseEmptyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResponseEmptyValidationError) ErrorName() string { return "ResponseEmptyValidationError" }

// Error satisfies the builtin error interface
func (e ResponseEmptyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResponseEmpty.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResponseEmptyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResponseEmptyValidationError{}

// Validate checks the field values on DownloadRequestMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DownloadRequestMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DownloadRequestMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DownloadRequestMessageMultiError, or nil if none found.
func (m *DownloadRequestMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *DownloadRequestMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Path

	if len(errors) > 0 {
		return DownloadRequestMessageMultiError(errors)
	}

	return nil
}

// DownloadRequestMessageMultiError is an error wrapping multiple validation
// errors returned by DownloadRequestMessage.ValidateAll() if the designated
// constraints aren't met.
type DownloadRequestMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DownloadRequestMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DownloadRequestMessageMultiError) AllErrors() []error { return m }

// DownloadRequestMessageValidationError is the validation error returned by
// DownloadRequestMessage.Validate if the designated constraints aren't met.
type DownloadRequestMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DownloadRequestMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DownloadRequestMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DownloadRequestMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DownloadRequestMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DownloadRequestMessageValidationError) ErrorName() string {
	return "DownloadRequestMessageValidationError"
}

// Error satisfies the builtin error interface
func (e DownloadRequestMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDownloadRequestMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DownloadRequestMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DownloadRequestMessageValidationError{}

// Validate checks the field values on DownloadResponseMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DownloadResponseMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DownloadResponseMessage with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DownloadResponseMessageMultiError, or nil if none found.
func (m *DownloadResponseMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *DownloadResponseMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Chunk

	if len(errors) > 0 {
		return DownloadResponseMessageMultiError(errors)
	}

	return nil
}

// DownloadResponseMessageMultiError is an error wrapping multiple validation
// errors returned by DownloadResponseMessage.ValidateAll() if the designated
// constraints aren't met.
type DownloadResponseMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DownloadResponseMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DownloadResponseMessageMultiError) AllErrors() []error { return m }

// DownloadResponseMessageValidationError is the validation error returned by
// DownloadResponseMessage.Validate if the designated constraints aren't met.
type DownloadResponseMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DownloadResponseMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DownloadResponseMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DownloadResponseMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DownloadResponseMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DownloadResponseMessageValidationError) ErrorName() string {
	return "DownloadResponseMessageValidationError"
}

// Error satisfies the builtin error interface
func (e DownloadResponseMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDownloadResponseMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DownloadResponseMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DownloadResponseMessageValidationError{}
