// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: apu/server_file/server_file.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *UploadMessage) Reset() {
	*x = UploadMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apu_server_file_server_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMessage) ProtoMessage() {}

func (x *UploadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_apu_server_file_server_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMessage.ProtoReflect.Descriptor instead.
func (*UploadMessage) Descriptor() ([]byte, []int) {
	return file_apu_server_file_server_file_proto_rawDescGZIP(), []int{0}
}

func (x *UploadMessage) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type ResponseEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResponseEmpty) Reset() {
	*x = ResponseEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apu_server_file_server_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEmpty) ProtoMessage() {}

func (x *ResponseEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_apu_server_file_server_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEmpty.ProtoReflect.Descriptor instead.
func (*ResponseEmpty) Descriptor() ([]byte, []int) {
	return file_apu_server_file_server_file_proto_rawDescGZIP(), []int{1}
}

type DownloadRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *DownloadRequestMessage) Reset() {
	*x = DownloadRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apu_server_file_server_file_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequestMessage) ProtoMessage() {}

func (x *DownloadRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_apu_server_file_server_file_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequestMessage.ProtoReflect.Descriptor instead.
func (*DownloadRequestMessage) Descriptor() ([]byte, []int) {
	return file_apu_server_file_server_file_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadRequestMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *DownloadResponseMessage) Reset() {
	*x = DownloadResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apu_server_file_server_file_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponseMessage) ProtoMessage() {}

func (x *DownloadResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_apu_server_file_server_file_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponseMessage.ProtoReflect.Descriptor instead.
func (*DownloadResponseMessage) Descriptor() ([]byte, []int) {
	return file_apu_server_file_server_file_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadResponseMessage) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_apu_server_file_server_file_proto protoreflect.FileDescriptor

var file_apu_server_file_server_file_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x75, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2c, 0x0a, 0x16, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x2f, 0x0a, 0x17, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x32, 0x7e, 0x0a, 0x0b, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x12, 0x3f, 0x0a, 0x08, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x17, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18,
	0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x30, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x67, 0x75, 0x79, 0x65, 0x6e, 0x74,
	0x72, 0x75, 0x6e, 0x67, 0x68, 0x69, 0x65, 0x75, 0x31, 0x35, 0x2f, 0x76, 0x63, 0x73, 0x2d, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x70, 0x72, 0x6a, 0x2f, 0x61, 0x70, 0x75, 0x2f, 0x66, 0x69,
	0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apu_server_file_server_file_proto_rawDescOnce sync.Once
	file_apu_server_file_server_file_proto_rawDescData = file_apu_server_file_server_file_proto_rawDesc
)

func file_apu_server_file_server_file_proto_rawDescGZIP() []byte {
	file_apu_server_file_server_file_proto_rawDescOnce.Do(func() {
		file_apu_server_file_server_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_apu_server_file_server_file_proto_rawDescData)
	})
	return file_apu_server_file_server_file_proto_rawDescData
}

var file_apu_server_file_server_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apu_server_file_server_file_proto_goTypes = []interface{}{
	(*UploadMessage)(nil),           // 0: UploadMessage
	(*ResponseEmpty)(nil),           // 1: ResponseEmpty
	(*DownloadRequestMessage)(nil),  // 2: DownloadRequestMessage
	(*DownloadResponseMessage)(nil), // 3: DownloadResponseMessage
}
var file_apu_server_file_server_file_proto_depIdxs = []int32{
	0, // 0: FileService.UploadFile:input_type -> UploadMessage
	2, // 1: FileService.Download:input_type -> DownloadRequestMessage
	1, // 2: FileService.UploadFile:output_type -> ResponseEmpty
	3, // 3: FileService.Download:output_type -> DownloadResponseMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apu_server_file_server_file_proto_init() }
func file_apu_server_file_server_file_proto_init() {
	if File_apu_server_file_server_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apu_server_file_server_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apu_server_file_server_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apu_server_file_server_file_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apu_server_file_server_file_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apu_server_file_server_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apu_server_file_server_file_proto_goTypes,
		DependencyIndexes: file_apu_server_file_server_file_proto_depIdxs,
		MessageInfos:      file_apu_server_file_server_file_proto_msgTypes,
	}.Build()
	File_apu_server_file_server_file_proto = out.File
	file_apu_server_file_server_file_proto_rawDesc = nil
	file_apu_server_file_server_file_proto_goTypes = nil
	file_apu_server_file_server_file_proto_depIdxs = nil
}
